import { SvgIcon } from "./components/svg/SvgIcon";
import {
  DataHome,
  DataAbout,
  PageComponents,
  PageComponentsAccordion,
  PageComponentsAlert,
  PageComponentsAudio,
  PageComponentsBadge,
  PageComponentsButton,
  PageComponentsCard,
  DataContact,
  PageComponentsVideo,
} from "./pages";

export const PagesData = [
  {
    id: "1",
    url: "/",
    title: "Home",
    hideNav: true,
    content: DataHome,
  },
  {
    id: "2",
    url: "/components",
    title: "Components",
    content: PageComponents,
  },
  {
    id: "2-1",
    url: "/components/accordion",
    title: "Accordion",
    hideNav: true,
    theme: "pink",
    content: PageComponentsAccordion,
  },
  {
    id: "2-2",
    url: "/components/alert",
    title: "Alert",
    hideNav: true,
    theme: "blue",
    content: PageComponentsAlert,
  },
  {
    id: "2-3",
    url: "/components/audio",
    title: "Audio",
    hideNav: true,
    theme: "green",
    content: PageComponentsAudio,
  },
  {
    id: "2-4",
    url: "/components/badge",
    title: "Badge",
    hideNav: true,
    theme: "purple",
    content: PageComponentsBadge,
  },
  {
    id: "2-5",
    url: "/components/button",
    title: "Button",
    hideNav: true,
    theme: "red",
    content: PageComponentsButton,
  },
  {
    id: "2-6",
    url: "/components/card",
    title: "Card",
    hideNav: true,
    theme: "orange",
    content: PageComponentsCard,
  },
  {
    id: "2-7",
    url: "/components/video",
    title: "Video",
    hideNav: true,
    theme: "orange",
    content: PageComponentsVideo,
  },
  {
    id: "3",
    url: "/about",
    title: "About",
    content: DataAbout,
  },
  {
    id: "4",
    url: "/contact",
    title: "Contact",
    content: DataContact,
  },
];
